{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e93d0942-47ec-47c2-91e8-c96c3d319900",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-06-14 14:35:42.069 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.129 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.134 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.367 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.368 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.377 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.380 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.382 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.390 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.414 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.651 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.663 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.669 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.670 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.686 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:42.841 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.885 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.886 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.887 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.888 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.890 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.893 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.948 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.949 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.951 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:44.953 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.001 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.002 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-06-14 14:35:45.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# PAGE CONFIG\n",
    "# ---------------------------------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"South Korea Top 50 Analytics\",\n",
    "    page_icon=\"🎵\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"🎵 South Korea Top 50 Playlist Analytics\")\n",
    "st.markdown(\"### Comeback Momentum, Chart Re-Entry & Fandom Intensity Analysis\")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# LOAD DATA\n",
    "# ---------------------------------------------------\n",
    "uploaded_file = st.sidebar.file_uploader(\n",
    "    \"Upload CSV Dataset\",\n",
    "    type=[\"csv\"]\n",
    ")\n",
    "\n",
    "if uploaded_file is None:\n",
    "    st.info(\"Upload the South Korea Top 50 Playlist CSV file.\")\n",
    "    st.stop()\n",
    "\n",
    "df = pd.read_csv('Atlantic_South_Korea.csv')\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# DATA PREPROCESSING\n",
    "# ---------------------------------------------------\n",
    "df[\"date\"] = pd.to_datetime(\n",
    "    df[\"date\"],\n",
    "    dayfirst=True\n",
    ")\n",
    "\n",
    "df[\"song_artist\"] = (\n",
    "    df[\"song\"].astype(str)\n",
    "    + \" - \"\n",
    "    + df[\"artist\"].astype(str)\n",
    ")\n",
    "\n",
    "df[\"duration_min\"] = df[\"duration_ms\"] / 60000\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# SIDEBAR FILTERS\n",
    "# ---------------------------------------------------\n",
    "st.sidebar.header(\"Filters\")\n",
    "\n",
    "artists = sorted(df[\"artist\"].dropna().unique())\n",
    "\n",
    "selected_artist = st.sidebar.selectbox(\n",
    "    \"Artist\",\n",
    "    [\"All\"] + artists\n",
    ")\n",
    "\n",
    "album_filter = st.sidebar.multiselect(\n",
    "    \"Album Type\",\n",
    "    options=df[\"album_type\"].dropna().unique(),\n",
    "    default=list(df[\"album_type\"].dropna().unique())\n",
    ")\n",
    "\n",
    "date_range = st.sidebar.date_input(\n",
    "    \"Date Range\",\n",
    "    [df[\"date\"].min(), df[\"date\"].max()]\n",
    ")\n",
    "\n",
    "filtered = df.copy()\n",
    "\n",
    "if selected_artist != \"All\":\n",
    "    filtered = filtered[\n",
    "        filtered[\"artist\"] == selected_artist\n",
    "    ]\n",
    "\n",
    "filtered = filtered[\n",
    "    filtered[\"album_type\"].isin(album_filter)\n",
    "]\n",
    "\n",
    "filtered = filtered[\n",
    "    (filtered[\"date\"] >= pd.to_datetime(date_range[0]))\n",
    "    &\n",
    "    (filtered[\"date\"] <= pd.to_datetime(date_range[1]))\n",
    "]\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# KPI CALCULATIONS\n",
    "# ---------------------------------------------------\n",
    "song_dates = (\n",
    "    filtered\n",
    "    .sort_values([\"song_artist\", \"date\"])\n",
    ")\n",
    "\n",
    "song_dates[\"gap\"] = (\n",
    "    song_dates\n",
    "    .groupby(\"song_artist\")[\"date\"]\n",
    "    .diff()\n",
    "    .dt.days\n",
    ")\n",
    "\n",
    "song_dates[\"reentry\"] = np.where(\n",
    "    song_dates[\"gap\"] > 1,\n",
    "    1,\n",
    "    0\n",
    ")\n",
    "\n",
    "reentry_df = (\n",
    "    song_dates\n",
    "    .groupby(\"song_artist\")[\"reentry\"]\n",
    "    .sum()\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "rank_stats = (\n",
    "    filtered\n",
    "    .groupby(\"song_artist\")[\"position\"]\n",
    "    .agg([\"min\", \"max\", \"mean\"])\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "rank_stats[\"rank_jump\"] = (\n",
    "    rank_stats[\"max\"]\n",
    "    - rank_stats[\"min\"]\n",
    ")\n",
    "\n",
    "pop_stats = (\n",
    "    filtered\n",
    "    .groupby(\"song_artist\")\n",
    "    .agg(\n",
    "        avg_popularity=(\"popularity\", \"mean\"),\n",
    "        max_popularity=(\"popularity\", \"max\")\n",
    "    )\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "momentum = pd.merge(\n",
    "    rank_stats,\n",
    "    pop_stats,\n",
    "    on=\"song_artist\"\n",
    ")\n",
    "\n",
    "momentum[\"momentum_score\"] = (\n",
    "    momentum[\"rank_jump\"]\n",
    "    * momentum[\"mean\"]\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# FANDOM INTENSITY SCORE\n",
    "# ---------------------------------------------------\n",
    "fandom = pd.merge(\n",
    "    reentry_df,\n",
    "    momentum[\n",
    "        [\n",
    "            \"song_artist\",\n",
    "            \"momentum_score\"\n",
    "        ]\n",
    "    ],\n",
    "    on=\"song_artist\"\n",
    ")\n",
    "\n",
    "scaler = MinMaxScaler()\n",
    "\n",
    "fandom[\n",
    "    [\"reentry_scaled\",\n",
    "     \"momentum_scaled\"]\n",
    "] = scaler.fit_transform(\n",
    "    fandom[\n",
    "        [\"reentry\",\n",
    "         \"momentum_score\"]\n",
    "    ]\n",
    ")\n",
    "\n",
    "fandom[\"fandom_score\"] = (\n",
    "    fandom[\"reentry_scaled\"] * 0.6\n",
    "    +\n",
    "    fandom[\"momentum_scaled\"] * 0.4\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# KPI CARDS\n",
    "# ---------------------------------------------------\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "\n",
    "col1.metric(\n",
    "    \"Songs\",\n",
    "    filtered[\"song_artist\"].nunique()\n",
    ")\n",
    "\n",
    "col2.metric(\n",
    "    \"Artists\",\n",
    "    filtered[\"artist\"].nunique()\n",
    ")\n",
    "\n",
    "col3.metric(\n",
    "    \"Total Records\",\n",
    "    len(filtered)\n",
    ")\n",
    "\n",
    "col4.metric(\n",
    "    \"Re-Entries\",\n",
    "    int(reentry_df[\"reentry\"].sum())\n",
    ")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# RE-ENTRY ANALYSIS\n",
    "# ---------------------------------------------------\n",
    "st.header(\"📈 Re-Entry Analysis\")\n",
    "\n",
    "top_reentry = (\n",
    "    reentry_df\n",
    "    .sort_values(\n",
    "        \"reentry\",\n",
    "        ascending=False\n",
    "    )\n",
    "    .head(15)\n",
    ")\n",
    "\n",
    "fig1 = px.bar(\n",
    "    top_reentry,\n",
    "    x=\"song_artist\",\n",
    "    y=\"reentry\",\n",
    "    title=\"Top Re-Entered Songs\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(\n",
    "    fig1,\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# MOMENTUM ANALYSIS\n",
    "# ---------------------------------------------------\n",
    "st.header(\"🚀 Momentum Analysis\")\n",
    "\n",
    "top_momentum = (\n",
    "    momentum\n",
    "    .sort_values(\n",
    "        \"momentum_score\",\n",
    "        ascending=False\n",
    "    )\n",
    "    .head(15)\n",
    ")\n",
    "\n",
    "fig2 = px.bar(\n",
    "    top_momentum,\n",
    "    x=\"song_artist\",\n",
    "    y=\"momentum_score\",\n",
    "    title=\"Momentum Spike Score\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(\n",
    "    fig2,\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# POPULARITY TREND\n",
    "# ---------------------------------------------------\n",
    "st.header(\"🔥 Popularity Trends\")\n",
    "\n",
    "daily_popularity = (\n",
    "    filtered\n",
    "    .groupby(\"date\")[\"popularity\"]\n",
    "    .mean()\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "fig3 = px.line(\n",
    "    daily_popularity,\n",
    "    x=\"date\",\n",
    "    y=\"popularity\",\n",
    "    title=\"Average Popularity Over Time\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(\n",
    "    fig3,\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# CONTENT ANALYSIS\n",
    "# ---------------------------------------------------\n",
    "st.header(\"🎧 Content Analysis\")\n",
    "\n",
    "album_chart = (\n",
    "    filtered\n",
    "    .groupby(\"album_type\")\n",
    "    .agg(\n",
    "        avg_popularity=(\"popularity\", \"mean\")\n",
    "    )\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "fig4 = px.pie(\n",
    "    album_chart,\n",
    "    names=\"album_type\",\n",
    "    values=\"avg_popularity\",\n",
    "    title=\"Album Type Distribution\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(\n",
    "    fig4,\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# Explicit Analysis\n",
    "explicit_chart = (\n",
    "    filtered\n",
    "    .groupby(\"is_explicit\")\n",
    "    .agg(\n",
    "        popularity=(\"popularity\", \"mean\")\n",
    "    )\n",
    "    .reset_index()\n",
    ")\n",
    "\n",
    "fig5 = px.bar(\n",
    "    explicit_chart,\n",
    "    x=\"is_explicit\",\n",
    "    y=\"popularity\",\n",
    "    title=\"Explicit vs Non-Explicit Popularity\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(\n",
    "    fig5,\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# FANDOM LEADERBOARD\n",
    "# ---------------------------------------------------\n",
    "st.header(\"🏆 Fandom Intensity Leaderboard\")\n",
    "\n",
    "leaderboard = (\n",
    "    fandom\n",
    "    .sort_values(\n",
    "        \"fandom_score\",\n",
    "        ascending=False\n",
    "    )\n",
    ")\n",
    "\n",
    "st.dataframe(\n",
    "    leaderboard.head(20),\n",
    "    use_container_width=True\n",
    ")\n",
    "\n",
    "# ---------------------------------------------------\n",
    "# DOWNLOAD SECTION\n",
    "# ---------------------------------------------------\n",
    "st.header(\"📥 Download Reports\")\n",
    "\n",
    "csv = leaderboard.to_csv(index=False)\n",
    "\n",
    "st.download_button(\n",
    "    label=\"Download Fandom Leaderboard CSV\",\n",
    "    data=csv,\n",
    "    file_name=\"fandom_leaderboard.csv\",\n",
    "    mime=\"text/csv\"\n",
    ")\n",
    "\n",
    "st.success(\"Dashboard Loaded Successfully\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0de1ed51-70e7-4faa-a93a-7951feae452d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
